### ISSUE TITLE
Grand Unified TODO List

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#125]
We are tracking here the features and enhancements which should or will be implemented in the near future.
#### New APIs
- [ ] CoAP
- [ ] MQTT
- [x] W3C Sensors
- [x] File (Node.js)
- [x] HTTP (Node.js)
- [x] Console (Node.js)
- [x] Web USB (native)
#### Build
- [x] Update Zephyr and JerryScript to latest (now on 1.5 and 1.0)
- [x] Fix make clean to remove prj.conf and src/Makefile (PR #300)
- [X] Fix make clean to work even when tree is already clean (James)
- [ ] Fix make to set ZEPHYR_BASE if not set
- [x] Add warning with helpful message if zephyr-env.sh hasn't been sourced
- [x] Add error with helpful message if zjs-env.sh hasn't been sourced (ZJS_BASE missing)
- [x] Check for nonexistent JS file rather than passing through to obscure minify error
#### Documentation
- [ ] Add memory consumption numbers to wiki
- [ ] Add matrix to indicate which APIs _should_ work on each supported boards
#### API documentation
- [x] GPIO
- [x] AIO
- [x] PWM
- [x] BLE
- [x] A101 pins
- [x] K64F pins
- [x] Buffer

**Comment by grgustaf** [comment]
Closing, because this idea of a permanent issue wasn't too bright. I captured the two documentation requests on my own todo list.
